### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by gplusdotgr** [chronotruck/webpack-stats-diff-action#19]
Warning: Unexpected input(s) 'token', valid inputs are ['base_stats_path', 'head_stats_path']
Run chronotruck/webpack-stats-diff-action@1.0.0
/usr/bin/docker exec  6f2d67d7ba14993f1095c0b5e4e729ce52b893a728748685b10b887018de372b sh -c "cat /etc/*release | grep ^ID"

even though the diff is posted, I keep getting this warning. 

```yaml
compare:
    runs-on: self-hosted
    container: docker-ro.visable.com/wlw_node:14.14.0-alpine
    name: Compare base & head bundle sizes
    needs:
    - build-base
    - build-head
    steps:
    - uses: actions/checkout@v2
    - name: Download base artifact
      uses: actions/download-artifact@v2
      with:
        name: base
        path: "./stats/base"
    - name: Download head artifact
      uses: actions/download-artifact@v2
      with:
        name: head
        path: "./stats/head"
    - name: Diff between base & head
      uses: chronotruck/webpack-stats-diff-action@1.0.0
      with:
        base_stats_path: "./stats/base/modern.json"
        head_stats_path: "./stats/head/modern.json"
        token: "${{ secrets.GITHUB_TOKEN }}"
```
